### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by zanaviska** [haixuanTao/bert-onnx-rs-pipeline#1]
I tried to install your solution locally, and came up with 2 errors:
1) _Download the data https://www.kaggle.com/START-UMD/gtd -> train_October_9_2012.csv and put it in the folder training._
By that link I have found file **globalterrorismdb_0718dist.csv**. If this file works, You should update filename, otherwise link to the file
2) `pip install -r requirements.txt`
this command produce error
```
ERROR: Invalid requirement: 'version https://git-lfs.github.com/spec/v1' (from line 1 of requirement.txt)
Hint: It looks like a path. File 'version https://git-lfs.github.com/spec/v1' does not exist.
```

**Comment by haixuanTao** [comment]
Yeah, so you need git lfs for this project. I added it into the README. Check https://git-lfs.github.com/

I have made it possible to run `pip install -r requirements.txt` without git lfs, but you might face other problem later for larger files.

**Comment by zanaviska** [comment]
Okay, thanks for that. But question about .csv file still exist. Which file is correct one? Should I really go for train_October_9_2012.csv? Or globalterrorismdb_0718dist.csv is good for me?

**Comment by haixuanTao** [comment]
Ah good catch. The actual good link is the following: https://www.kaggle.com/c/predict-closed-questions-on-stack-overflow/data?select=train_October_9_2012.csv

**Comment by haixuanTao** [comment]
Thanks for the issue!
